### ISSUE TITLE
One parent should be treated as canonical

### ISSUE THREAD

**Issue by mughal4** [setr/redsystem#16]
Categories with only one parent should be treated as canonical and given a page with parentcategory/category with the parentcategory hyperlinked in the header.

**Comment by mughal4** [comment]
proposed model:
If a dirname exists, it's the category's dirname.
Else if one parent exists, then its the dirname.
Otherwise, no dirname

if a dirname exists, there must also exist a category of the same name and all users of the dirname are implicitly children of the associated category

**Comment by setr** [comment]
same as #11
