### ISSUE TITLE
naming conventions proposed changes

### ISSUE THREAD

**Issue by mughal4** [setr/redsystem#20]
parents to parent
aliases to alias
description to title
to reduce awkwardness and follow mainstream naming paradigms.

alias="example"
should be accepted alongside alias=["example"] in cases where there is only one tag to reduce excessive typing effort. current format lends itself to multiple tags but is excessive for single tags.

**Comment by setr** [comment]
Use serde attribute [#[serde(deserialize_with = "path")]](https://serde.rs/field-attrs.html)

[Example](https://github.com/serde-rs/serde/issues/889)

**Comment by setr** [comment]
All changes were implemented as described.
